In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('dimention: ',arr.ndim)
print('shape: ',arr.shape)
print("total elemts: ",arr.size)
print("item size",arr.itemsize)
print("data type", arr.dtype)
print('toatal: ',arr.nbytes)

dimention:  2
shape:  (3, 3)
total elemts:  9
item size 8
data type int64
toatal:  72


In [13]:
arr = np.array([[1,2,3],[4,0,6],[7,8,9]])
x = np.array(arr,dtype ='double')

print(x)


[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [14]:
import numpy as np
y= np.arange(0,11,1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
import numpy as np
z= np.arange(1,25).reshape(2,3,4)
print(z)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
#creating 4d array using range  function
import numpy as np
z= np.arange(1,61).reshape(2,3,2,5)
print(z)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[31 32 33 34 35]
   [36 37 38 39 40]]

  [[41 42 43 44 45]
   [46 47 48 49 50]]

  [[51 52 53 54 55]
   [56 57 58 59 60]]]]


#create 6X6 mtrx which is filled with zero except border that is filled with one


In [17]:
import numpy  as np
arr = np.zeros([6,6])
print(arr)
print()
arr[0:1] = [1]
arr[5:6] = [1]
print(arr[0:1,0:6])
print()
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]]


In [18]:
# import matplotlib.pyplot as plt

# import numpy as np
# x= np.linspace(0,4*np.pi,1000)
# y=np.sin(x)
# z=range(len(y))
# plt.plot(z,y)
# plt.show()

In [19]:
# creat an array of 15 value alternating 1,0,1,0,1
count =0
arr=[]
for i in range(15):
    if(count ==0):
        arr.append(1)
        count=1
    else:
        arr.append(0)
        count=0
print(arr)
print()


[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]



In [20]:
import numpy  as np
arr =np.full((3,3),True)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [21]:
import numpy as np
arr =np.ones([3,3],dtype=bool)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [22]:
arr =np.arange(1,10).reshape(3,3)
print(arr)
arr=arr.astype(bool)
print()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
arr =np.eye(5,4,dtype=bool)
print(arr)


[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]
 [False False False False]]


In [24]:
arr =np.eye(4,4,dtype=int)
print(arr)
arr =np.eye(4,4,-1,dtype=int)
print("eye matrin")
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
eye matrin
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [25]:
arr =np.identity(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
arr =np.arange(1,10)
print(arr)
arr =np.diag(arr)
print(arr)
print()
arr =np.arange(1,10).reshape(3,3)
print(arr)
print()
arr =np.diag(arr)
print(arr)


[1 2 3 4 5 6 7 8 9]
[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]


In [27]:
arr =np.arange(11,20).reshape(3,3)
print(arr)
x=[1,-2]
y=[0,-1]
print(arr[x,y])

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[14 16]


In [28]:
import numpy as np

arr = np.arange(1,28).reshape(3, 3, 3)   

print(arr)

x = [0, 1]
y = [1, 1]
z = [0, 1]  

print("\n")
print(arr[x, y, z])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


[ 4 14]


In [29]:
arr= np.arange(1,10)
print(arr)
print(arr[arr>5]){:lkyhg}
print(arr[arr%2==0])

SyntaxError: invalid syntax (1301272910.py, line 3)

In [ ]:
import numpy as np
import random 
#1-D array with float value from 0 to 1
a= np.random.rand()
print(a)
#2-D array with float value from 0 to 1
print("2-D")
b= np.random.rand(35)
print(b)
print("3-D")
#3-D array with float value from 0 to 1
c= np.random.rand(2,3,4)
print(c)


0.047082876120429495
2-D
[0.2099522  0.72246234 0.6928319  0.81619085 0.45191088 0.25141061
 0.5883898  0.35978318 0.27831479 0.54120523 0.34514921 0.63464305
 0.86654193 0.79754492 0.77654962 0.9859582  0.61821027 0.6317815
 0.35903944 0.61822565 0.2848567  0.37949322 0.55659823 0.25545483
 0.88572301 0.75242455 0.53632908 0.02571135 0.24866589 0.26368541
 0.01511325 0.46815165 0.02788468 0.90276945 0.23100662]
3-D
[[[0.04226687 0.35986381 0.3408051  0.54562873]
  [0.3155041  0.04886067 0.69733356 0.9213408 ]
  [0.91518463 0.58632613 0.37331579 0.25271248]]

 [[0.34272309 0.58058704 0.02894802 0.12281911]
  [0.73096888 0.17628089 0.86081859 0.8139616 ]
  [0.52412016 0.26368075 0.49104181 0.03952129]]]


In [ ]:
print(np.random.uniform(10,20))

18.241097657652183


In [8]:
print(np.random.uniform(10,20,size=10))

[14.707192   16.17609844 17.08064538 15.75747053 15.08161766 19.25831985
 10.07267144 18.88286892 13.14893657 12.33544365]


In [10]:
print(np.random.uniform(10,20,size =(3,5)))

[[17.02710369 11.78101413 19.47207441 13.80928965 18.10151349]
 [18.78293672 16.70361504 15.9968523  18.93646456 15.90814845]
 [10.57906336 11.21911981 13.5649919  10.41740471 11.85177895]]


In [11]:
print(np.random.uniform(10,20,size= (2,3,4)))

[[[12.77844231 18.6816465  10.93091867 14.26125829]
  [15.3776439  19.03822417 11.57090477 10.76146481]
  [19.30003389 19.05336893 12.5544026  16.89916277]]

 [[13.29429464 17.68680869 18.06213751 17.59838759]
  [12.55859862 14.68756108 14.22315626 17.00781543]
  [11.51926099 19.1992661  18.44760936 15.66045174]]]


In [ ]:
# pANDAS

In [32]:
import pandas as pd
s = pd.Series([20], index=[13], dtype=int)
print(s)


13    20
dtype: int64


In [33]:
s1= pd.Series([10,20,30,40])
print(s1)

0    10
1    20
2    30
3    40
dtype: int64


In [47]:
s2 = pd.Series([1,2,3,4],['a','b','c','d'])
print(s2)
print(s2.index)
print(s2.values)
print(s1.dtype)

a    1
b    2
c    3
d    4
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')
[1 2 3 4]
int64


In [48]:
# generat a series print consttant value
s3 = pd.Series(data=[range(0,20)],index=[range(0,20)])
print(s3)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)    (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
dtype: object


In [56]:
# generate a series with constant value 0 for indices 0 to 19
s3 = pd.Series(data=[np.random.randint(1,10)]* 20, index=range(0,20))
print(s3)

0     6
1     6
2     6
3     6
4     6
5     6
6     6
7     6
8     6
9     6
10    6
11    6
12    6
13    6
14    6
15    6
16    6
17    6
18    6
19    6
dtype: int64


In [ ]:
y = [chr(i) for i in range(65,71)]   
x = np.random.randint(10,31, size=6)  
s5 = pd.Series(x, index=y)
print(s5)


A    20
B    18
C    14
D    29
E    26
F    14
dtype: int32


In [69]:
# slicing and indexing in a series

print(s5[0])
print()
print(s5[:3])       


print(s5[[0,5,3]])
print("________________________________________________________________________________________________________________________________")
print(s5.iloc[0])
print()
print(s5.iloc[0:4])
print()
print(s5.iloc[[0,5,3]])


20

A    20
B    18
C    14
dtype: int32
A    20
F    14
D    29
dtype: int32
________________________________________________________________________________________________________________________________
20

A    20
B    18
C    14
D    29
dtype: int32

A    20
F    14
D    29
dtype: int32


C:\Users\navia\AppData\Local\Temp\ipykernel_28892\1114319807.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s5[0])
C:\Users\navia\AppData\Local\Temp\ipykernel_28892\1114319807.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s5[[0,5,3]])


In [ ]:
# fin the even elements in the series


print(s5[s5%2==0])


A    20
B    18
C    14
E    26
F    14
dtype: int32


In [72]:
print(s5+10)
print(s5*2)

A    30
B    28
C    24
D    39
E    36
F    24
dtype: int32
A    40
B    36
C    28
D    58
E    52
F    28
dtype: int32


In [74]:
print(s5.describe())
print(s5.mean())
print(s5.std())
print(s5.sum())
print(s5.min())
print(s5.max())
print(s5.tails())
print(s5.head())


count     6.000000
mean     20.166667
std       6.210207
min      14.000000
25%      15.000000
50%      19.000000
75%      24.500000
max      29.000000
dtype: float64
20.166666666666668
6.210206652492868
121
14
29


AttributeError: 'Series' object has no attribute 'tails'